export const SQS_DEFAULT_WAIT_TIME = 20;
export const SQS_DEFAULT_VISIBILITY_TIMEOUT = 300;
export const SQS_POLL_INTERVAL_ON_ERROR = 5000;
export const SQS_DEFAULT_CONCURRENCY = 10;
export const SQS_MAX_MESSAGES_PER_POLL = 10;

export const SYNC_ERROR_STATUS_MAP: Record<string, number> = {
  CLONE_FAILED: 502,
  FETCH_FAILED: 502,
  BUNDLE_FAILED: 500,
  UPLOAD_FAILED: 502,
  CLEANUP_FAILED: 500,
  INVALID_WEBHOOK: 401,
  REPO_NOT_TRACKED: 404,
  INTEGRATION_INACTIVE: 400,
  SYNC_IN_PROGRESS: 409,
  SYNC_JOB_NOT_FOUND: 404,
};
