export const INTEGRATION_ERROR_STATUS_MAP: Record<string, number> = {
  ALREADY_CONNECTED: 409,
  INTEGRATION_NOT_FOUND: 404,
  INVALID_CREDENTIALS: 401,
  OAUTH_FAILED: 400,
  TOKEN_EXPIRED: 401,
  TOKEN_REFRESH_FAILED: 401,
  CONNECTION_TEST_FAILED: 502,
};
