export const REPOSITORY_ERROR_STATUS_MAP: Record<string, number> = {
  REPO_NOT_FOUND: 404,
  REPO_ALREADY_TRACKED: 409,
  INTEGRATION_NOT_FOUND: 404,
  STORAGE_NOT_CONFIGURED: 400,
  SYNC_FAILED: 502,
  WEBHOOK_SETUP_FAILED: 502,
  PROVIDER_ERROR: 502,
};
